#! /usr/bin/zsh

source /usr/lib/spaceship-prompt/spaceship.zsh

autoload -U colors
autoload -U promptinit; promptinit

colors

setopt PROMPT_SUBST

prompt spaceship
setopt CORRECT
setopt CORRECTALL

setopt hist_ignore_dups     # ignore duplication command history list
setopt share_history        # share command history data
setopt HIST_IGNORE_SPACE
setopt APPEND_HISTORY # write history only when closing
setopt EXTENDED_HISTORY # add more info

autoload url-quote-magic
zle -N self-insert url-quote-magic

# Load completions for Ruby, Git, etc.
autoload compinit
compinit

HISTFILE=~/.zsh_history
SAVEHIST=10000
HISTSIZE=10000

LISTMAX=0 # Ask to complete if top of list would scroll off screen

# Make CTRL-W delete after other chars, not just spaces
WORDCHARS=${WORDCHARS//[&=\/;\!#%\{]}

bindkey -e

bindkey "\e[3~" delete-char

# Auto CD
setopt autocd
